### PR TITLE
Edi view errors

### LINKED ISSUE #511: Build "view errors" for edi management
Page will display entries in table edi_error_report.  
Investigate possible options to limit display by date, or by date/time.

Usual sorting ability by clicking on column header.

Users will get to view errors page in 2 ways:

1. Choose the option "view errors" in libsys-webforms, and put in a date (and time??) 
Should then view all errors for that date (and that time or later?)
Or put in both start time and end time, and return all lines in the table between those times?

2. When edi processing runs, users get an email with a URL

old form URL: http://sulohsprod1.stanford.edu/library/batch/EDI_ERROR.display_error?p_date_time=19-apr-2017%2009:16:00&p_end_time=19-apr-2017%2009:16:08&p_range=ALL&p_level=notify

new form URL should be similar to this (for the batch updates errors):
https://libsys-webforms.stanford.edu/batch_record_updates/errors_for_batch?utf8=✓&batch_number=28901&commit=Go

The old form URL (and PL/SQL procedure it calls) shows errors between p_date_time and p_end_time (this is start and end time for the edi_processing run that generated the URL, i.e., user sees errors only for the one processing run).

It would be nice to be able to replicate the "show the errors for one processing run" by sending in a start and end time to a libsys-webforms URL, as well as the date to display.

### PR DESCRIPTION
**Pull request by jgreben**
Fixes #511

### CODE REVIEW

**Comment by jgreben** [comment]
Still need to fix error with Oracle date query, and absence of DataTable for edi_error_report.

**Comment by jgreben** [comment]
@dlrueda This is ready for review. Merge if you like or we can wait until I am back from vacation.

**Comment by dlrueda** [comment]
The date sort doesn't seem to be working on libsys-webforms-dev.  Clicking on the "run" column header while looking at "all days" doesn't change the order at all.

**Comment by dlrueda** [comment]
I like the "Show errors for today" button.  And I know one can update the URL address directly and put in the specific date they want to see errors for.  That is very cool.

But I'm wondering if there can also be a date widget somewhere on the page to be able to specify a date?  So they can see the errors for whatever day they choose (last Friday's for instance on Monday of the next week).  Not critical, and perhaps wait and see if the users also ask for this.  

Rita will ask the users to review what is now deployed to libsys-webforms-dev.

**Pull request merged**
