### PR TITLE
Makes authorized users admin tables more readable

### PR DESCRIPTION
**Pull request by jgreben**

### CODE REVIEW

**Comment by shelleydoljack** [comment]
I cannot add a user; the form doesn't render correctly. And sure enough, we don't have any views tests for authorized users.

**Comment by jgreben** [comment]
> I cannot add a user; the form doesn't render correctly. And sure enough, we don't have any views tests for authorized users.

This is fixed.

**Review by shelleydoljack — CHANGES_REQUESTED** [review]
When I try to add a user, the submit button doesn't appear in the modal in Chrome:
Screen Shot 2020-01-15 at 1 41 53 PM
In Safari, the submit button appears but the bottom of the modal seems cut off.
Screen Shot 2020-01-15 at 1 44 11 PM
If it's easier to put this on a page instead of a modal, then go ahead.

**Comment by jgreben** [comment]
@shelleydoljack this should be fixed now

**Review by shelleydoljack — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
