### PR TITLE
remove datepicker js and use default rails/html5 datepicker

### LINKED ISSUE #686: Remove bootstrap datepicker
In Chrome and Firefox, multiple calendar popups appear for a date field now that browsers support the html5 calendar popup.

### PR DESCRIPTION
**Pull request by jgreben**
Fixes #686

### CODE REVIEW

**Review by shelleydoljack — CHANGES_REQUESTED** [review]
But it breaks the date picker in Safari.

**Comment by jgreben** [comment]
@shelleydoljack I think breaking the datepicker in Safari is the lesser of two evils in this case. The only other option would be to try to figure out a way to do a browser detection and conditionally use the needed `date_field` but that seems like a lot of undesirable complexity.

**Comment by dlrueda** [comment]
I think @rlunnon should check with users to see what browsers most folks are using.  Am I understanding correctly that some browsers will break at this point, unless we check for what browser it is and conditionally use the date_field, as Josh says below?  (gross)

**Comment by jgreben** [comment]
@shelleydoljack @dlrueda @rlunnon I added the HTML5 Webshim polyfiller to this so that it will automatically emulate the datepicker functionality for browsers that are not html5 compliant.

**Review by shelleydoljack — APPROVED** [review]
I think this is better. Thanks for adding the webshim. Hopefully Safari and Edge will implement the HTML5 date field but it looks like it's been broken like this for a few years now.

**Pull request merged**
