### PR TITLE
Fix fy

### PR DESCRIPTION
**Pull request by jgreben**
We had the wrong fiscal year defined. It should be xxxx-09-01 to xxxx-08-31, and the first date should be the last calendar year (i.e. FY2017 should be 2016-09-01 to 2017-08-31)

### CODE REVIEW

**Comment by jgreben** [comment]
@dlrueda please review and merge when you get a chance.

**Comment by dlrueda** [comment]
This logic won't work (I don't think) for the months September-December, when the year should be the SAME year as current date (for beginning date), not subtract one year.  Also the end date will have to have a year added to it during Sept-Dec.

But this will work for the immediate fix.  We need an issue to either set the year depending on what the current date is, or refactor to fiscal year lookup. I will have Rita ask the Acq folks which makes more sense.

**Comment by dlrueda** [comment]
Actually, I looked at the form, and the selection is for fiscal year (nothing about dates).  So I'll add an issue to refactor this to actually use the fiscal year column in that table.

**Comment by jgreben** [comment]
I don't think this will be a problem because the month and day (9/1 and 8/31) do not change for the FY query. Only the year changes.

Josh

On Apr 20, 2017, at 12:09 PM, Darsi Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


This logic won't work (I don't think) for the months September-December, when the year should be the SAME year as current date (for beginning date), not subtract one year. Also the end date will have to have a year added to it during Sept-Dec.

But this will work for the immediate fix. We need an issue to either set the year depending on what the current date is, or refactor to fiscal year lookup. I will have Rita ask the Acq folks which makes more sense.

**Comment by dlrueda** [comment]
Sorry, mis-understood the code.  Was thinking you were looking at current date, not at fiscal year chosen.  Thanks for straightening me out!

**Pull request merged**
